project:
  type: website
  output-dir: docs


website:
  title: BN Notes
  site-url: https://beyond-notability.github.io/bn_notes/
  favicon: profile.jpg
  navbar:
    left:
      - text: Posts
        href: blog.qmd
      - text: Notes
        href: notes/index.qmd        
    right:
      - text: Beyond Notability
        href: https://beyondnotability.org/
      - text: Database
        href: https://beyond-notability.wikibase.cloud/wiki/Main_Page
      - icon: github
        href: https://github.com/Beyond-Notability/bn_notes
        aria-label: Github

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    code-fold: true


date-format: "D MMMM YYYY"


# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)

freeze: auto

